# permissions for end users to view grants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: grant-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgresql-operator
    app.kubernetes.io/part-of: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: grant-viewer-role
rules:
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - grants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - grants/status
  verbs:
  - get
